name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build:
    name: Build release
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            cross: false
            strip: true
          - target: x86_64-unknown-linux-musl
            cross: true
            strip: true
          - target: i686-unknown-linux-gnu
            cross: true
            strip: true
          - target: i686-unknown-linux-musl
            cross: true
            strip: true
          - target: aarch64-unknown-linux-gnu
            cross: true
            strip: false
          - target: aarch64-unknown-linux-musl
            cross: true
            strip: false

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build binaries
        uses: ClementTsang/cargo-action@v0.0.6
        with:
          command: build
          args: --locked --release --target=${{ matrix.target }}
          use-cross: ${{ matrix.cross }}

      - name: Strip binaries
        run: strip target/${{ matrix.target }}/release/mihoro
        if: ${{ matrix.strip }}

      - name: Package binaries
        run: |
          cd target/${{ matrix.target }}/release
          tar -czvf mihoro-${{ github.ref_name }}-${{ matrix.target }}.tar.gz mihoro
          cd -

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/${{ matrix.target }}/release/mihoro-${{ github.ref_name }}-${{ matrix.target }}.tar.gz
          asset_name: mihoro-${{ github.ref_name }}-${{ matrix.target }}.tar.gz
          tag: ${{ github.ref }}
          draft: true

  publish:
    name: Publish complete release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Publish release
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
          RELEASE_TAG: ${{ github.ref_name }}
        run: gh release edit "$RELEASE_TAG" --draft=false --latest
